name: Telebot CI/CD
on:
  push:
    branches: develop
jobs:
  ci:
      name: CI
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        - name: Run test
          run: make test
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }} 
        - name: Build&Push
          env:
            APP_NAME: "helm-telebot"
            REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          run: make image push     
  cd:
      needs: ci
      runs-on: ubuntu-latest     
      steps:   
        - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
        - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        - uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)' helm-telebot/values.yaml
        
  
